In [ ]:
# numpy.ipynb

In [ ]:
# numpy çok boyutlu diziler için hızlı cebirsel işlemler yapar.
# python da listelerde çok boyutlu olabilir. Fakat numpy dizileri(ndarray-n dimension array) python listelerinden 50 kat daha hızlı işlem yapar.

In [1]:
l0=5 #0d - skaler
l1 =[5] # 1d-vektör - (1,)
l2=[[5]] #2d-matris-(1,1)
l3=[[[5]]] #3d-tensör-(1,1,1)

In [3]:
l22=[[1,2],[3,45]] # 2d-(2,2)->4

In [4]:
l23=[[3,4,5,3],[5,6,68,72],[33,33,72,2],[78,98,36,7]]#2d (4,4)
print(l23[1][3])

72


In [10]:
l33=[
    [[1,2,30],[25,3,25]],
    [[22,30,25],[25,98,78]],
    [[58,87,78],[2,3,8]]
    ]
#3d-(3,2,3)
print(l33[1][1][1])
print(l33[2][0][0])

98
58


In [18]:
import numpy as np

l33=[
    [[1,2,30],[25,3,25]],
    [[22,30,25],[25,98,78]],
    [[58,87,78],[2,3,8]]
    ]
r1 = np.array(l33)
print(r1.shape)
print(r1.ndim)
print(r1.sum())
print(r1.size)
print(r1+3)



(3, 2, 3)
3
600
18
[[[  4   5  33]
  [ 28   6  28]]

 [[ 25  33  28]
  [ 28 101  81]]

 [[ 61  90  81]
  [  5   6  11]]]
