In [ ]:
# regresyon_duz_ysa.ipynb

In [1]:
import pandas as pd
import numpy as np

In [2]:
veri = pd.read_csv("regresyon_veri2.csv")
veri.head(5)

ozellik1  ozellik2  sinif-hedef
0        10         5           38
1        20        30           93
2         3         2           14
3         5         8           26
4         7        10           34

In [3]:
ort=veri.mean()
std =veri.std()
veri = (veri-ort)/std

veri.head(5)

ozellik1  ozellik2  sinif-hedef
0 -0.706900 -0.829696    -0.811129
1 -0.372826 -0.091532    -0.323991
2 -0.940752 -0.918275    -1.023698
3 -0.873937 -0.741116    -0.917414
4 -0.807122 -0.682063    -0.846557

In [4]:
print(ort)
print(std)

ozellik1        31.16
ozellik2        33.10
sinif-hedef    129.58
dtype: float64
ozellik1        29.933505
ozellik2        33.867840
sinif-hedef    112.904346
dtype: float64


In [6]:
X = veri.iloc[:,:-1].values # tensör veya matris
y = veri.iloc[:,-1].values # vektör

In [7]:
import tensorflow as tf
from keras import layers,models,optimizers

2023-11-28 17:39:48.511701: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-11-28 17:39:48.535383: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-11-28 17:39:48.660266: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-11-28 17:39:48.660311: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-11-28 17:39:48.660993: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to regi

In [10]:
ysa = models.Sequential()
ysa.add(layers.Dense(256,input_shape=(2,),activation="relu"))
ysa.add(layers.Dense(128,activation="relu"))
ysa.add(layers.Dense(1)) # activation function eklenmiyor çünkü sayı tahmini yapılacak
ysa.compile(optimizer="rmsprop",loss="mse",metrics=["mae"])

#callback eklenecek 28.11.2023


In [11]:
print(ysa.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 256)               768       
                                                                 
 dense_4 (Dense)             (None, 128)               32896     
                                                                 
 dense_5 (Dense)             (None, 1)                 129       
                                                                 
Total params: 33793 (132.00 KB)
Trainable params: 33793 (132.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [ ]:
kayit = ysa.fit(X,y,epochs=200,validation_split=0.2)

In [15]:
test_veri=np.array([[8,7],[3,10]])

test_veri_n=(test_veri-ort.values[0:2])/std.values[0:2]
test_veri_n


array([[-0.77371495, -0.77064258],
       [-0.94075186, -0.68206298]])

In [16]:
tahmin = ysa.predict(test_veri_n)
tahmin

1/1 [==============================] - 0s 41ms/step


array([[-0.81291014],
       [-0.89454836]], dtype=float32)

In [17]:
tahmin_d=tahmin*std.values[2]+ort.values[2]
tahmin_d

array([[37.79892 ],
       [28.581604]], dtype=float32)