In [9]:
# regresyon_ysa.ipynb
import pandas as pd
import numpy as np

In [10]:
veri = pd.read_csv("regresyon_veri2.csv")
veri.head()

ozellik1  ozellik2  sinif-hedef
0        10         5           38
1        20        30           93
2         3         2           14
3         5         8           26
4         7        10           34

In [11]:
#verileri normalize ediyoruz -1,1 aralığna sıkıştırıyoruz.
ort = veri.mean()
std=veri.std()
veri_ham=veri.copy()
veri = (veri-ort)/std
veri.head()

ozellik1  ozellik2  sinif-hedef
0 -0.706900 -0.829696    -0.811129
1 -0.372826 -0.091532    -0.323991
2 -0.940752 -0.918275    -1.023698
3 -0.873937 -0.741116    -0.917414
4 -0.807122 -0.682063    -0.846557

In [12]:
print(ort)
print(std)

ozellik1        31.16
ozellik2        33.10
sinif-hedef    129.58
dtype: float64
ozellik1        29.933505
ozellik2        33.867840
sinif-hedef    112.904346
dtype: float64


In [13]:
X = veri.iloc[:,:-1].values
y = veri.iloc[:,-1].values
print(X[0:5])
print(30*"-")
print(y[0:5])

[[-0.70690019 -0.82969565]
 [-0.37282638 -0.09153226]
 [-0.94075186 -0.91827526]
 [-0.8739371  -0.74111605]
 [-0.80712233 -0.68206298]]
------------------------------
[-0.81112909 -0.32399107 -1.02369841 -0.91741375 -0.84655731]


In [14]:
import tensorflow as tf
import keras
from keras import layers,models,optimizers
from keras.callbacks import ModelCheckpoint

In [15]:
ysa = models.Sequential()
ysa.add(layers.Dense(16,input_shape=(2,),activation="relu"))
ysa.add(layers.Dense(8,activation="relu"))
ysa.add(layers.Dense(1)) # regresyon tahminlemesi olacağı için aktivasyon fonksiyonu eklemiyorum

ysa.compile(optimizer="rmsprop",loss="mse",metrics=["mae"])

print(ysa.summary())



Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 16)                48        
                                                                 
 dense_4 (Dense)             (None, 8)                 136       
                                                                 
 dense_5 (Dense)             (None, 1)                 9         
                                                                 
Total params: 193 (772.00 Byte)
Trainable params: 193 (772.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [16]:
hikaye = ysa.fit(X,y,epochs=100,validation_split=0.2)

Epoch 1/100


2/2 [==============================] - 0s 71ms/step - loss: 0.7013 - mae: 0.7704 - val_loss: 0.2752 - val_mae: 0.4867
Epoch 2/100
2/2 [==============================] - 0s 14ms/step - loss: 0.6323 - mae: 0.7331 - val_loss: 0.2660 - val_mae: 0.4817
Epoch 3/100
2/2 [==============================] - 0s 14ms/step - loss: 0.5838 - mae: 0.7076 - val_loss: 0.2457 - val_mae: 0.4628
Epoch 4/100
2/2 [==============================] - 0s 15ms/step - loss: 0.5488 - mae: 0.6861 - val_loss: 0.2297 - val_mae: 0.4480
Epoch 5/100
2/2 [==============================] - 0s 16ms/step - loss: 0.5168 - mae: 0.6650 - val_loss: 0.2209 - val_mae: 0.4418
Epoch 6/100
2/2 [==============================] - 0s 15ms/step - loss: 0.4842 - mae: 0.6466 - val_loss: 0.2110 - val_mae: 0.4331
Epoch 7/100
2/2 [==============================] - 0s 14ms/step - loss: 0.4573 - mae: 0.6297 - val_loss: 0.2003 - val_mae: 0.4225
Epoch 8/100
2/2 [==============================] - 0s 15ms/step - loss: 0.4351 - mae: 0.6143 - val_los

In [17]:
degerler=np.array([[3,8],[7,2]])

# yukarıdaki ort ve std pandas veri tipidir.
degerler_n=(degerler-ort.values[0:2])/std.values[0:2]

degerler_n


array([[-0.94075186, -0.74111605],
       [-0.80712233, -0.91827526]])

In [18]:
tahminler=ysa.predict(degerler_n)
print(tahminler)

1/1 [==============================] - 0s 43ms/step
[[-0.9582789]
 [-0.913993 ]]


In [19]:
tahminler_dn = tahminler*std.values[-1]+ort.values[-1]
print(tahminler_dn)

[[21.386154]
 [26.386223]]
